import time
from google import genai
from config.settings import GEMINI_API_KEY

client = genai.Client(api_key=GEMINI_API_KEY)

MODELS = [
    "gemini-2.5-flash-lite",
    "gemini-2.5-flash",
    "gemini-2.0-flash",
]


def ask_gemini(prompt):

    last_error = None

    for model in MODELS:

        for attempt in range(5):

            try:

                response = client.models.generate_content(
                    model=model,
                    contents=prompt,
                )

                if response.text:
                    return response.text.strip()

            except Exception as e:

                last_error = e

                print(f"{model} Attempt {attempt + 1}: {e}")

                time.sleep((attempt + 1) * 5)

    raise last_error


def generate_title(title, summary):

    prompt = f"""
You are an SEO expert.

Create ONE compelling blog title.

Requirements:

- English only
- Maximum 60 characters
- Click-worthy
- SEO optimized
- Remove author names
- Remove website names
- Remove @mentions
- Remove "via"

News Title:
{title}

Summary:
{summary}

Return ONLY the title.
"""

    return ask_gemini(prompt)


def get_prompt(category, title, summary):

    return f"""
You are an expert Digital Marketing Content Writer and SEO Specialist.

Write a premium-quality, human-like blog article.

Category:
{category}

Title:
{title}

Summary:
{summary}

Requirements:

- Language: English
- Original content
- Human writing style
- Professional tone
- SEO optimized
- No AI-sounding text
- No repetition
- Easy to read
- Include actionable insights
- HTML only
- 1000–1500 words

Use this structure:

<h1>{title}</h1>

<h2>Introduction</h2>

<h2>What Happened?</h2>

<h2>Key Highlights</h2>

<h2>Why This Matters</h2>

<h2>Impact on Digital Marketers</h2>

<h2>Expert Analysis</h2>

<h2>Best Practices</h2>

<ul>
<li>5-7 actionable takeaways</li>
</ul>

<h2>Frequently Asked Questions</h2>

Include 3 relevant questions and detailed answers.

<h2>Conclusion</h2>

End the article with:

<p><strong>Stay updated with the latest AI, SEO, Google, Meta, Adobe, and Digital Marketing news on SocialFlux AI.</strong></p>

Rules:

- Use proper HTML tags only.
- Do NOT use Markdown.
- Do NOT mention that the article was generated by AI.
- Make the article engaging, informative, and optimized for Google search.
"""

    return prompt


def write_article(category, title, summary):

    prompt = get_prompt(
        category,
        title,
        summary
    )

    return ask_gemini(prompt)
